jobs:
  - job: Ubuntu_AutoTools_GCC
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: 'Linux (GCC + Autotools)'
    strategy:
      matrix:
        Default:
          CONFIGURE_OPTS: ''
        --enable-64-bit-words:
          CONFIGURE_OPTS: '--enable-64-bit-words'
    steps:
    - script: sudo apt-get install -y libtool-bin libogg-dev
      displayName: Install dependencies
    - script: ./autogen.sh
      displayName: Bootstrap
    - script: ./configure $(CONFIGURE_OPTS)
      displayName: Configure
    - script: make
      displayName: Build
    - script: make check
      displayName: Test

  - job: Ubuntu_AutoTools_Clang
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: 'Linux (Clang + Autotools)'
    strategy:
      matrix:
        Default:
          CONFIGURE_OPTS: ''
        --enable-64-bit-words:
          CONFIGURE_OPTS: '--enable-64-bit-words'
    steps:
    - script: sudo apt-get install -y libtool-bin clang libogg-dev
      displayName: Install dependencies
    - script: |
        export CC=clang
        export CXX=clang++
      displayName: Set Clang as C\C++ compiler
    - script: ./autogen.sh
      displayName: Bootstrap
    - script: ./configure $(CONFIGURE_OPTS)
      displayName: Configure
    - script: make
      displayName: Build
    - script: make check
      displayName: Test

  - job: macOS_AutoTools_AppleClang
    pool:
      vmImage: 'macOS-10.14'
    displayName: 'macOS (AppleClang + Autotools)'
    strategy:
      matrix:
        Default:
          CONFIGURE_OPTS: ''
        --enable-64-bit-words:
          CONFIGURE_OPTS: '--enable-64-bit-words'
    steps:
    - script: brew install autoconf automake libtool pkg-config libogg
      displayName: Install dependencies
    - script: ./autogen.sh
      displayName: Bootsrap
    - script: ./configure $(CONFIGURE_OPTS)
      displayName: Configure
    - script: make
      displayName: Build
    - script: make check
      displayName: Test