jobs:
  - job: Ubuntu_AutoTools
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: 'Linux (Autotools)'
    strategy:
      matrix:
        Default:
          CONFIGURE_OPTS: ''
        Enable64BitWords:
          CONFIGURE_OPTS: '--enable-64-bit-words'
    steps:
    - script: |
        sudo apt-get install -y libtool-bin libogg-dev
        ./autogen.sh
        ./configure $(CONFIGURE_OPTS)
        make
        make check
