jobs:
  - job: Ubuntu_AutoTools_GCC
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: 'Linux (GCC + Autotools)'
    strategy:
      matrix:
        Default:
          CONFIGURE_OPTS: ''
        --enable-64-bit-words:
          CONFIGURE_OPTS: '--enable-64-bit-words'
    steps:
    - script: |
        sudo apt-get install -y libtool-bin libogg-dev
        ./autogen.sh
        ./configure $(CONFIGURE_OPTS)
        make
        make check

  - job: Ubuntu_AutoTools_Clang
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: 'Linux (Clang + Autotools)'
    strategy:
      matrix:
        Default:
          CONFIGURE_OPTS: ''
        --enable-64-bit-words:
          CONFIGURE_OPTS: '--enable-64-bit-words'
    steps:
    - script: |
        sudo apt-get install -y libtool-bin clang libogg-dev
        export CC=clang
        export CXX=clang++
        ./autogen.sh
        ./configure $(CONFIGURE_OPTS)
        make
        make check

jobs:
  - job: macOS_AutoTools_GCC
    pool:
      vmImage: 'macOS-10.13'
    displayName: 'macOS (GCC + Autotools)'
    strategy:
      matrix:
        Default:
          CONFIGURE_OPTS: ''
        --enable-64-bit-words:
          CONFIGURE_OPTS: '--enable-64-bit-words'
    steps:
    - script: |
        brew install libogg
        ./autogen.sh
        ./configure $(CONFIGURE_OPTS)
        make
        make check